"""add_recurring_transactions

Revision ID: 30851f39d362
Revises: 87143b249b24
Create Date: 2025-12-01 02:26:34.716988

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30851f39d362"
down_revision: str | None = "87143b249b24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create enum types first
    transaction_status = postgresql.ENUM(
        "scheduled", "posted", "skipped", name="transaction_status", create_type=False
    )
    transaction_status.create(op.get_bind(), checkfirst=True)

    frequency_unit = postgresql.ENUM(
        "days", "weeks", "months", "years", name="frequency_unit", create_type=False
    )
    frequency_unit.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "recurring_transactions",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("payee_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("frequency_value", sa.Integer(), nullable=False),
        sa.Column(
            "frequency_unit",
            postgresql.ENUM(
                "days",
                "weeks",
                "months",
                "years",
                name="frequency_unit",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("memo", sa.String(length=500), nullable=True),
        sa.Column("next_occurrence_date", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["payee_id"], ["payees.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recurring_transactions_team_id",
        "recurring_transactions",
        ["team_id"],
        unique=False,
    )
    op.create_index(
        "ix_recurring_transactions_team_next_occurrence",
        "recurring_transactions",
        ["team_id", "next_occurrence_date"],
        unique=False,
    )
    op.add_column(
        "transactions",
        sa.Column(
            "status",
            postgresql.ENUM(
                "scheduled",
                "posted",
                "skipped",
                name="transaction_status",
                create_type=False,
            ),
            nullable=False,
            server_default="posted",
        ),
    )
    op.add_column(
        "transactions", sa.Column("recurring_transaction_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "transactions", sa.Column("occurrence_index", sa.Integer(), nullable=True)
    )
    op.add_column(
        "transactions",
        sa.Column("is_modified", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.create_index(
        "ix_transactions_recurring_id",
        "transactions",
        ["recurring_transaction_id"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_team_status_date_id",
        "transactions",
        ["team_id", "status", "date", "id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "transactions",
        "recurring_transactions",
        ["recurring_transaction_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "transactions_recurring_transaction_id_fkey", "transactions", type_="foreignkey"
    )
    op.drop_index("ix_transactions_team_status_date_id", table_name="transactions")
    op.drop_index("ix_transactions_recurring_id", table_name="transactions")
    op.drop_column("transactions", "is_modified")
    op.drop_column("transactions", "occurrence_index")
    op.drop_column("transactions", "recurring_transaction_id")
    op.drop_column("transactions", "status")
    op.drop_index(
        "ix_recurring_transactions_team_next_occurrence",
        table_name="recurring_transactions",
    )
    op.drop_index(
        "ix_recurring_transactions_team_id", table_name="recurring_transactions"
    )
    op.drop_table("recurring_transactions")

    # Drop enum types
    postgresql.ENUM(name="transaction_status").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="frequency_unit").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
