"""add allocation_rules table

Revision ID: 521e5b39909f
Revises: 974da1cfb2f4
Create Date: 2025-12-05 06:24:00.682693

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "521e5b39909f"
down_revision: str | None = "974da1cfb2f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allocation_rules",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("envelope_id", sa.Uuid(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("rule_type", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("is_percentage", sa.Boolean(), nullable=False),
        sa.Column("cap", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["envelope_id"], ["envelopes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_allocation_rules_team_envelope",
        "allocation_rules",
        ["team_id", "envelope_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_allocation_rules_team_id"),
        "allocation_rules",
        ["team_id"],
        unique=False,
    )
    op.create_index(
        "ix_allocation_rules_team_priority",
        "allocation_rules",
        ["team_id", "priority"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_allocation_rules_team_priority", table_name="allocation_rules")
    op.drop_index(op.f("ix_allocation_rules_team_id"), table_name="allocation_rules")
    op.drop_index("ix_allocation_rules_team_envelope", table_name="allocation_rules")
    op.drop_table("allocation_rules")
    # ### end Alembic commands ###
