"""add_report_indexes

Revision ID: 539ded95b0b8
Revises: a1b2c3d4e5f6
Create Date: 2025-12-06 19:24:03.692130

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "539ded95b0b8"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_transactions_team_location_id",
        "transactions",
        ["team_id", "location_id"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_team_payee_id",
        "transactions",
        ["team_id", "payee_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_team_payee_id", table_name="transactions")
    op.drop_index("ix_transactions_team_location_id", table_name="transactions")
    # ### end Alembic commands ###
