"""add_notifications_tables

Revision ID: 6667d8b38881
Revises: 539ded95b0b8
Create Date: 2025-12-06 20:10:33.498521

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6667d8b38881"
down_revision: str | None = "539ded95b0b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_preferences",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "notification_type",
            postgresql.ENUM(
                "low_balance",
                "upcoming_expense",
                "recurring_not_funded",
                "goal_reached",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("low_balance_threshold", sa.BigInteger(), nullable=True),
        sa.Column("upcoming_expense_days", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "team_id", "user_id", "notification_type", name="uq_notification_pref"
        ),
    )
    op.create_index(
        "ix_notification_preferences_team_user",
        "notification_preferences",
        ["team_id", "user_id"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "notification_type",
            postgresql.ENUM(
                "low_balance",
                "upcoming_expense",
                "recurring_not_funded",
                "goal_reached",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("related_entity_type", sa.String(length=50), nullable=True),
        sa.Column("related_entity_id", sa.UUID(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("is_dismissed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_team_id"), "notifications", ["team_id"], unique=False
    )
    op.create_index(
        "ix_notifications_team_type",
        "notifications",
        ["team_id", "notification_type"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_team_user_read",
        "notifications",
        ["team_id", "user_id", "is_read"],
        unique=False,
    )
    op.add_column(
        "envelopes",
        sa.Column(
            "goal_reached_notified_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("envelopes", "goal_reached_notified_at")
    op.drop_index("ix_notifications_team_user_read", table_name="notifications")
    op.drop_index("ix_notifications_team_type", table_name="notifications")
    op.drop_index(op.f("ix_notifications_team_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        "ix_notification_preferences_team_user", table_name="notification_preferences"
    )
    op.drop_table("notification_preferences")
    # ### end Alembic commands ###
