"""update_fk_constraints

Revision ID: 67ca3dadd1cc
Revises: 709046d1ea5b
Create Date: 2025-12-02 12:50:00.139241

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67ca3dadd1cc"
down_revision: str | None = "709046d1ea5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("recurring_transactions_payee_id_fkey"),
        "recurring_transactions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "recurring_transactions",
        "payees",
        ["payee_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        op.f("transactions_payee_id_fkey"), "transactions", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("transactions_linked_transaction_id_fkey"),
        "transactions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "transactions", "payees", ["payee_id"], ["id"], ondelete="RESTRICT"
    )
    op.create_foreign_key(
        None,
        "transactions",
        "transactions",
        ["linked_transaction_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.create_foreign_key(
        op.f("transactions_linked_transaction_id_fkey"),
        "transactions",
        "transactions",
        ["linked_transaction_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("transactions_payee_id_fkey"),
        "transactions",
        "payees",
        ["payee_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "recurring_transactions", type_="foreignkey")
    op.create_foreign_key(
        op.f("recurring_transactions_payee_id_fkey"),
        "recurring_transactions",
        "payees",
        ["payee_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
