"""add_transfer_support

Revision ID: 709046d1ea5b
Revises: b9afc8c43f9b
Create Date: 2025-12-01 13:50:03.721222

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "709046d1ea5b"
down_revision: str | None = "b9afc8c43f9b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recurring_transactions",
        sa.Column("destination_account_id", sa.Uuid(), nullable=True),
    )
    op.alter_column(
        "recurring_transactions", "payee_id", existing_type=sa.UUID(), nullable=True
    )
    op.create_foreign_key(
        None,
        "recurring_transactions",
        "accounts",
        ["destination_account_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "transactions", sa.Column("linked_transaction_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        "ix_transactions_linked_id",
        "transactions",
        ["linked_transaction_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "transactions",
        "transactions",
        ["linked_transaction_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_index("ix_transactions_linked_id", table_name="transactions")
    op.drop_column("transactions", "linked_transaction_id")
    op.drop_constraint(None, "recurring_transactions", type_="foreignkey")
    op.alter_column(
        "recurring_transactions", "payee_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("recurring_transactions", "destination_account_id")
    # ### end Alembic commands ###
