"""add_is_reconciled_to_transactions

Revision ID: 739661c8319f
Revises: 321e1c2010cd
Create Date: 2025-12-23 14:32:00.052678

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "739661c8319f"
down_revision: str | None = "321e1c2010cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "is_reconciled", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    op.create_index(
        "ix_transactions_team_reconciled_date_id",
        "transactions",
        ["team_id", "is_reconciled", "date", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_team_reconciled_date_id", table_name="transactions")
    op.drop_column("transactions", "is_reconciled")
    # ### end Alembic commands ###
