"""adds envelope groups and fixes allocation rule type

Revision ID: 79f4329bad93
Revises: d15bf40d0f86
Create Date: 2025-12-06 16:38:11.527123

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79f4329bad93"
down_revision: str | None = "d15bf40d0f86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "envelope_groups",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("icon", sa.String(length=10), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "name", name="uq_team_envelope_group_name"),
    )
    op.create_index(
        op.f("ix_envelope_groups_team_id"), "envelope_groups", ["team_id"], unique=False
    )

    # Create the enum type first
    allocation_rule_type = postgresql.ENUM(
        "fill_to_target",
        "fixed",
        "percentage",
        "remainder",
        name="allocation_rule_type",
    )
    allocation_rule_type.create(op.get_bind(), checkfirst=True)

    # Alter the column using the USING clause to cast existing values
    op.execute("""
        ALTER TABLE allocation_rules
        ALTER COLUMN rule_type TYPE allocation_rule_type
        USING rule_type::allocation_rule_type
    """)

    op.create_index(
        "ix_allocations_team_rule_id",
        "allocations",
        ["team_id", "allocation_rule_id"],
        unique=False,
    )
    op.add_column("envelopes", sa.Column("envelope_group_id", sa.Uuid(), nullable=True))
    op.create_index(
        "ix_envelopes_team_group_id",
        "envelopes",
        ["team_id", "envelope_group_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "envelopes",
        "envelope_groups",
        ["envelope_group_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "envelopes", type_="foreignkey")
    op.drop_index("ix_envelopes_team_group_id", table_name="envelopes")
    op.drop_column("envelopes", "envelope_group_id")
    op.drop_index("ix_allocations_team_rule_id", table_name="allocations")

    # Convert enum back to VARCHAR
    op.execute("""
        ALTER TABLE allocation_rules
        ALTER COLUMN rule_type TYPE VARCHAR(20)
        USING rule_type::text
    """)

    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS allocation_rule_type")

    op.drop_index(op.f("ix_envelope_groups_team_id"), table_name="envelope_groups")
    op.drop_table("envelope_groups")
    # ### end Alembic commands ###
