"""Add envelopes table

Revision ID: 87f476fc8dff
Revises: 67ca3dadd1cc
Create Date: 2025-12-04 20:47:20.362878

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87f476fc8dff"
down_revision: str | None = "67ca3dadd1cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "envelopes",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("icon", sa.String(length=10), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_unallocated", sa.Boolean(), nullable=False),
        sa.Column("current_balance", sa.BigInteger(), nullable=False),
        sa.Column("target_balance", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "name", name="uq_team_envelope_name"),
    )
    op.create_index(
        op.f("ix_envelopes_team_id"), "envelopes", ["team_id"], unique=False
    )
    op.create_index(
        "ix_envelopes_team_unallocated",
        "envelopes",
        ["team_id"],
        unique=True,
        postgresql_where=sa.text("is_unallocated = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_envelopes_team_unallocated",
        table_name="envelopes",
        postgresql_where=sa.text("is_unallocated = true"),
    )
    op.drop_index(op.f("ix_envelopes_team_id"), table_name="envelopes")
    op.drop_table("envelopes")
    # ### end Alembic commands ###
