"""

Revision ID: 90d244dd4c25
Revises: de9c2a1cfd39
Create Date: 2026-02-08 11:57:44.361957

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90d244dd4c25"
down_revision: str | None = "de9c2a1cfd39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("system_settings")
    op.drop_index(op.f("ix_allocation_rules_team_id"), table_name="allocation_rules")
    op.create_index(
        op.f("ix_allocation_rules_budget_id"),
        "allocation_rules",
        ["budget_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_allocations_team_id"), table_name="allocations")
    op.create_index(
        op.f("ix_allocations_budget_id"), "allocations", ["budget_id"], unique=False
    )
    op.drop_index(op.f("ix_envelopes_team_id"), table_name="envelopes")
    op.drop_index(
        op.f("ix_envelopes_team_unallocated"),
        table_name="envelopes",
        postgresql_where="(is_unallocated = true)",
    )
    op.create_index(
        op.f("ix_envelopes_budget_id"), "envelopes", ["budget_id"], unique=False
    )
    op.create_index(
        "ix_envelopes_budget_unallocated",
        "envelopes",
        ["budget_id"],
        unique=True,
        postgresql_where=sa.text("is_unallocated = true"),
    )
    op.drop_index(op.f("ix_notifications_team_id"), table_name="notifications")
    op.create_index(
        op.f("ix_notifications_budget_id"), "notifications", ["budget_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notifications_budget_id"), table_name="notifications")
    op.create_index(
        op.f("ix_notifications_team_id"), "notifications", ["budget_id"], unique=False
    )
    op.drop_index(
        "ix_envelopes_budget_unallocated",
        table_name="envelopes",
        postgresql_where=sa.text("is_unallocated = true"),
    )
    op.drop_index(op.f("ix_envelopes_budget_id"), table_name="envelopes")
    op.create_index(
        op.f("ix_envelopes_team_unallocated"),
        "envelopes",
        ["budget_id"],
        unique=True,
        postgresql_where="(is_unallocated = true)",
    )
    op.create_index(
        op.f("ix_envelopes_team_id"), "envelopes", ["budget_id"], unique=False
    )
    op.drop_index(op.f("ix_allocations_budget_id"), table_name="allocations")
    op.create_index(
        op.f("ix_allocations_team_id"), "allocations", ["budget_id"], unique=False
    )
    op.drop_index(op.f("ix_allocation_rules_budget_id"), table_name="allocation_rules")
    op.create_index(
        op.f("ix_allocation_rules_team_id"),
        "allocation_rules",
        ["budget_id"],
        unique=False,
    )
    op.create_table(
        "system_settings",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "registration_enabled",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("system_settings_pkey")),
    )
    # ### end Alembic commands ###
