"""Add allocations table

Revision ID: 974da1cfb2f4
Revises: 87f476fc8dff
Create Date: 2025-12-05 05:31:45.082916

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "974da1cfb2f4"
down_revision: str | None = "87f476fc8dff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allocations",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("envelope_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=True),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("execution_order", sa.Integer(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("memo", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["envelope_id"], ["envelopes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["transaction_id"], ["transactions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "team_id", "group_id", "execution_order", name="uq_allocation_group_order"
        ),
    )
    op.create_index(
        "ix_allocations_team_envelope_id",
        "allocations",
        ["team_id", "envelope_id"],
        unique=False,
    )
    op.create_index(
        "ix_allocations_team_group_id",
        "allocations",
        ["team_id", "group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_allocations_team_id"), "allocations", ["team_id"], unique=False
    )
    op.create_index(
        "ix_allocations_team_transaction_id",
        "allocations",
        ["team_id", "transaction_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_allocations_team_transaction_id", table_name="allocations")
    op.drop_index(op.f("ix_allocations_team_id"), table_name="allocations")
    op.drop_index("ix_allocations_team_group_id", table_name="allocations")
    op.drop_index("ix_allocations_team_envelope_id", table_name="allocations")
    op.drop_table("allocations")
    # ### end Alembic commands ###
