"""add_respect_target_to_allocation_rules

Revision ID: 9dc3013ee865
Revises: ef4e82e0826e
Create Date: 2025-12-11 13:45:21.903658

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9dc3013ee865"
down_revision: str | None = "ef4e82e0826e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "allocation_rules",
        sa.Column(
            "respect_target", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("allocation_rules", "respect_target")
    # ### end Alembic commands ###
