"""Add account_id to transactions

Revision ID: bc70a9ed73d5
Revises: ed08f9c46623
Create Date: 2025-11-30 19:14:47.014753

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc70a9ed73d5"
down_revision: str | None = "ed08f9c46623"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("account_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        None, "transactions", "accounts", ["account_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_column("transactions", "account_id")
    # ### end Alembic commands ###
