"""Initial migration

Revision ID: c2ce9b6db94f
Revises:
Create Date: 2026-02-10 21:30:14.184635

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2ce9b6db94f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("registration_enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "budgets",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("default_income_allocation", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=True
    )
    op.create_table(
        "accounts",
        sa.Column("budget_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "account_type",
            postgresql.ENUM(
                "checking",
                "savings",
                "money_market",
                "credit_card",
                "cash",
                "investment",
                "loan",
                "other",
                name="account_type",
            ),
            nullable=False,
        ),
        sa.Column("icon", sa.String(length=10), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("include_in_budget", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("cleared_balance", sa.BigInteger(), nullable=False),
        sa.Column("uncleared_balance", sa.BigInteger(), nullable=False),
        sa.Column("last_reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["budget_id"], ["budgets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("budget_id", "name", name="uq_budget_account_name"),
    )
    op.create_index(
        op.f("ix_accounts_budget_id"), "accounts", ["budget_id"], unique=False
    )
    op.create_table(
        "envelope_groups",
        sa.Column("budget_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("icon", sa.String(length=10), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["budget_id"], ["budgets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("budget_id", "name", name="uq_budget_envelope_group_name"),
    )
    op.create_index(
        op.f("ix_envelope_groups_budget_id"),
        "envelope_groups",
        ["budget_id"],
        unique=False,
    )
    op.create_table(
        "locations",
        sa.Column("budget_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("icon", sa.String(length=10), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["budget_id"], ["budgets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("budget_id", "name", name="uq_budget_location_name"),
    )
    op.create_index(
        op.f("ix_locations_budget_id"), "locations", ["budget_id"], unique=False
    )
    op.create_table(
        "notification_preferences",
        sa.Column("budget_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "notification_type",
            postgresql.ENUM(
                "low_balance",
                "upcoming_expense",
                "recurring_not_funded",
                "goal_reached",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("low_balance_threshold", sa.BigInteger(), nullable=True),
        sa.Column("upcoming_expense_days", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["budget_id"], ["budgets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "budget_id", "user_id", "notification_type", name="uq_notification_pref"
        ),
    )
    op.create_index(
        "ix_notification_preferences_budget_user",
        "notification_preferences",
        ["budget_id", "user_id"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("budget_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "notification_type",
            postgresql.ENUM(
                "low_balance",
                "upcoming_expense",
                "recurring_not_funded",
                "goal_reached",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("related_entity_type", sa.String(length=50), nullable=True),
        sa.Column("related_entity_id", sa.UUID(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("is_dismissed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["budget_id"], ["budgets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_budget_id"), "notifications", ["budget_id"], unique=False
    )
    op.create_index(
        "ix_notifications_budget_type",
        "notifications",
        ["budget_id", "notification_type"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_budget_user_read",
        "notifications",
        ["budget_id", "user_id", "is_read"],
        unique=False,
    )
    op.create_table(
        "user_budgets",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("budget_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("owner", "admin", "member", "viewer", name="budget_role"),
            nullable=False,
        ),
        sa.Column(
            "scope_additions",
            sa.ARRAY(sa.String(length=100)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "scope_removals",
            sa.ARRAY(sa.String(length=100)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["budget_id"], ["budgets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "budget_id", name="uq_user_budget"),
    )
    op.create_table(
        "envelopes",
        sa.Column("budget_id", sa.Uuid(), nullable=False),
        sa.Column("envelope_group_id", sa.Uuid(), nullable=True),
        sa.Column("linked_account_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("icon", sa.String(length=10), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_starred", sa.Boolean(), nullable=False),
        sa.Column("is_unallocated", sa.Boolean(), nullable=False),
        sa.Column("current_balance", sa.BigInteger(), nullable=False),
        sa.Column("target_balance", sa.BigInteger(), nullable=True),
        sa.Column(
            "goal_reached_notified_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["budget_id"], ["budgets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["envelope_group_id"], ["envelope_groups.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["linked_account_id"], ["accounts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("budget_id", "name", name="uq_budget_envelope_name"),
    )
    op.create_index(
        "ix_envelopes_budget_group_id",
        "envelopes",
        ["budget_id", "envelope_group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envelopes_budget_id"), "envelopes", ["budget_id"], unique=False
    )
    op.create_index(
        "ix_envelopes_budget_unallocated",
        "envelopes",
        ["budget_id"],
        unique=True,
        postgresql_where=sa.text("is_unallocated = true"),
    )
    op.create_index(
        "ix_envelopes_linked_account",
        "envelopes",
        ["linked_account_id"],
        unique=True,
        postgresql_where=sa.text("linked_account_id IS NOT NULL"),
    )
    op.create_table(
        "allocation_rules",
        sa.Column("budget_id", sa.Uuid(), nullable=False),
        sa.Column("envelope_id", sa.Uuid(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "rule_type",
            postgresql.ENUM(
                "fill_to_target",
                "fixed",
                "percentage",
                "remainder",
                "period_cap",
                name="allocation_rule_type",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("respect_target", sa.Boolean(), nullable=False),
        sa.Column("cap_period_value", sa.Integer(), nullable=False),
        sa.Column(
            "cap_period_unit",
            sa.Enum("WEEK", "MONTH", "YEAR", name="allocationcapperiodunit"),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["budget_id"], ["budgets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["envelope_id"], ["envelopes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_allocation_rules_budget_envelope",
        "allocation_rules",
        ["budget_id", "envelope_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_allocation_rules_budget_id"),
        "allocation_rules",
        ["budget_id"],
        unique=False,
    )
    op.create_index(
        "ix_allocation_rules_budget_priority",
        "allocation_rules",
        ["budget_id", "priority"],
        unique=False,
    )
    op.create_table(
        "payees",
        sa.Column("budget_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("icon", sa.String(length=10), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("default_envelope_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["budget_id"], ["budgets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["default_envelope_id"], ["envelopes.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("budget_id", "name", name="uq_budget_payee_name"),
    )
    op.create_index(op.f("ix_payees_budget_id"), "payees", ["budget_id"], unique=False)
    op.create_table(
        "recurring_transactions",
        sa.Column("budget_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("destination_account_id", sa.Uuid(), nullable=True),
        sa.Column("payee_id", sa.Uuid(), nullable=True),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("envelope_id", sa.Uuid(), nullable=True),
        sa.Column("frequency_value", sa.Integer(), nullable=False),
        sa.Column(
            "frequency_unit",
            postgresql.ENUM("days", "weeks", "months", "years", name="frequency_unit"),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("memo", sa.String(length=500), nullable=True),
        sa.Column("next_occurrence_date", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["budget_id"], ["budgets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["destination_account_id"], ["accounts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["envelope_id"], ["envelopes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["payee_id"], ["payees.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recurring_transactions_budget_id",
        "recurring_transactions",
        ["budget_id"],
        unique=False,
    )
    op.create_index(
        "ix_recurring_transactions_budget_next_occurrence",
        "recurring_transactions",
        ["budget_id", "next_occurrence_date"],
        unique=False,
    )
    op.create_table(
        "transactions",
        sa.Column("budget_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("payee_id", sa.Uuid(), nullable=True),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("is_cleared", sa.Boolean(), nullable=False),
        sa.Column("is_reconciled", sa.Boolean(), nullable=False),
        sa.Column("memo", sa.String(length=500), nullable=True),
        sa.Column(
            "transaction_type",
            postgresql.ENUM(
                "standard", "transfer", "adjustment", name="transaction_type"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "scheduled", "posted", "skipped", name="transaction_status"
            ),
            nullable=False,
        ),
        sa.Column("recurring_transaction_id", sa.Uuid(), nullable=True),
        sa.Column("occurrence_index", sa.Integer(), nullable=True),
        sa.Column("is_modified", sa.Boolean(), nullable=False),
        sa.Column("linked_transaction_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["budget_id"], ["budgets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["linked_transaction_id"], ["transactions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["payee_id"], ["payees.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["recurring_transaction_id"],
            ["recurring_transactions.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_transactions_budget_account_date_id",
        "transactions",
        ["budget_id", "account_id", "date", "id"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_budget_date_id",
        "transactions",
        ["budget_id", "date", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_budget_id"), "transactions", ["budget_id"], unique=False
    )
    op.create_index(
        "ix_transactions_budget_location_id",
        "transactions",
        ["budget_id", "location_id"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_budget_payee_id",
        "transactions",
        ["budget_id", "payee_id"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_budget_reconciled_date_id",
        "transactions",
        ["budget_id", "is_reconciled", "date", "id"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_budget_status_date_id",
        "transactions",
        ["budget_id", "status", "date", "id"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_linked_id",
        "transactions",
        ["linked_transaction_id"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_recurring_id",
        "transactions",
        ["recurring_transaction_id"],
        unique=False,
    )
    op.create_table(
        "allocations",
        sa.Column("budget_id", sa.Uuid(), nullable=False),
        sa.Column("envelope_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=True),
        sa.Column("allocation_rule_id", sa.Uuid(), nullable=True),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("execution_order", sa.Integer(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("memo", sa.String(length=500), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["allocation_rule_id"], ["allocation_rules.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["budget_id"], ["budgets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["envelope_id"], ["envelopes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["transaction_id"], ["transactions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "budget_id", "group_id", "execution_order", name="uq_allocation_group_order"
        ),
    )
    op.create_index(
        "ix_allocations_budget_envelope_date_id",
        "allocations",
        ["budget_id", "envelope_id", "date", "id"],
        unique=False,
    )
    op.create_index(
        "ix_allocations_budget_envelope_id",
        "allocations",
        ["budget_id", "envelope_id"],
        unique=False,
    )
    op.create_index(
        "ix_allocations_budget_group_id",
        "allocations",
        ["budget_id", "group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_allocations_budget_id"), "allocations", ["budget_id"], unique=False
    )
    op.create_index(
        "ix_allocations_budget_rule_id",
        "allocations",
        ["budget_id", "allocation_rule_id"],
        unique=False,
    )
    op.create_index(
        "ix_allocations_budget_transaction_id",
        "allocations",
        ["budget_id", "transaction_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_allocations_budget_transaction_id", table_name="allocations")
    op.drop_index("ix_allocations_budget_rule_id", table_name="allocations")
    op.drop_index(op.f("ix_allocations_budget_id"), table_name="allocations")
    op.drop_index("ix_allocations_budget_group_id", table_name="allocations")
    op.drop_index("ix_allocations_budget_envelope_id", table_name="allocations")
    op.drop_index("ix_allocations_budget_envelope_date_id", table_name="allocations")
    op.drop_table("allocations")
    op.drop_index("ix_transactions_recurring_id", table_name="transactions")
    op.drop_index("ix_transactions_linked_id", table_name="transactions")
    op.drop_index("ix_transactions_budget_status_date_id", table_name="transactions")
    op.drop_index(
        "ix_transactions_budget_reconciled_date_id", table_name="transactions"
    )
    op.drop_index("ix_transactions_budget_payee_id", table_name="transactions")
    op.drop_index("ix_transactions_budget_location_id", table_name="transactions")
    op.drop_index(op.f("ix_transactions_budget_id"), table_name="transactions")
    op.drop_index("ix_transactions_budget_date_id", table_name="transactions")
    op.drop_index("ix_transactions_budget_account_date_id", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(
        "ix_recurring_transactions_budget_next_occurrence",
        table_name="recurring_transactions",
    )
    op.drop_index(
        "ix_recurring_transactions_budget_id", table_name="recurring_transactions"
    )
    op.drop_table("recurring_transactions")
    op.drop_index(op.f("ix_payees_budget_id"), table_name="payees")
    op.drop_table("payees")
    op.drop_index("ix_allocation_rules_budget_priority", table_name="allocation_rules")
    op.drop_index(op.f("ix_allocation_rules_budget_id"), table_name="allocation_rules")
    op.drop_index("ix_allocation_rules_budget_envelope", table_name="allocation_rules")
    op.drop_table("allocation_rules")
    op.drop_index(
        "ix_envelopes_linked_account",
        table_name="envelopes",
        postgresql_where=sa.text("linked_account_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_envelopes_budget_unallocated",
        table_name="envelopes",
        postgresql_where=sa.text("is_unallocated = true"),
    )
    op.drop_index(op.f("ix_envelopes_budget_id"), table_name="envelopes")
    op.drop_index("ix_envelopes_budget_group_id", table_name="envelopes")
    op.drop_table("envelopes")
    op.drop_table("user_budgets")
    op.drop_index("ix_notifications_budget_user_read", table_name="notifications")
    op.drop_index("ix_notifications_budget_type", table_name="notifications")
    op.drop_index(op.f("ix_notifications_budget_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        "ix_notification_preferences_budget_user", table_name="notification_preferences"
    )
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_locations_budget_id"), table_name="locations")
    op.drop_table("locations")
    op.drop_index(op.f("ix_envelope_groups_budget_id"), table_name="envelope_groups")
    op.drop_table("envelope_groups")
    op.drop_index(op.f("ix_accounts_budget_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("budgets")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_table("system_settings")
    # ### end Alembic commands ###
