"""add_last_reconciled_at_to_accounts

Revision ID: ca00c6b0c8f2
Revises: 739661c8319f
Create Date: 2025-12-24 23:56:06.537925

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca00c6b0c8f2"
down_revision: str | None = "739661c8319f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column("last_reconciled_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "last_reconciled_at")
    # ### end Alembic commands ###
