"""add allocation_rule_id to allocations

Revision ID: d15bf40d0f86
Revises: 521e5b39909f
Create Date: 2025-12-05 06:35:22.824909

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d15bf40d0f86"
down_revision: str | None = "521e5b39909f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "allocations", sa.Column("allocation_rule_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "allocations",
        "allocation_rules",
        ["allocation_rule_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "allocations", type_="foreignkey")
    op.drop_column("allocations", "allocation_rule_id")
    # ### end Alembic commands ###
