"""add_description_to_accounts_payees_locations

Revision ID: f518c8be4033
Revises: 89cb0c3236ab
Create Date: 2025-11-30 18:45:35.518583

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f518c8be4033"
down_revision: str | None = "89cb0c3236ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts", sa.Column("description", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "locations", sa.Column("description", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "payees", sa.Column("description", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payees", "description")
    op.drop_column("locations", "description")
    op.drop_column("accounts", "description")
    # ### end Alembic commands ###
